version: '3.8'

services:
  db:
    image: timescale/timescaledb:latest-pg14
    container_name: timescaledb_dev
    ports:
      - "5433:5432"   #host:container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 25101974
      POSTGRES_DB: stock_screener
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5

  sample_loader:
    image: python:3.11-slim
    depends_on:
      - db
    volumes:
      - ./backend/database:/workspace
    working_dir: /workspace
    command: >
      bash -c "pip install -r requirements.txt && python sample_loader.py"

volumes:
  db_data:
